-- Locations seed data (real dataset: 50 rows)
INSERT INTO locations (location_id, name, layer, type, area, latitude, longitude)
VALUES
('EXT-C01', 'Agomeda Township', 'EXTERNAL', 'community', 'Shai-Osudoku District', NULL, NULL),
('EXT-C02', 'Asabe', 'EXTERNAL', 'community', 'Shai-Osudoku District', NULL, NULL),
('EXT-C03', 'Atsavanya', 'EXTERNAL', 'community', 'Shai-Osudoku District', NULL, NULL),
('EXT-C04', 'Dedenya', 'EXTERNAL', 'community', 'Shai-Osudoku District', NULL, NULL),
('EXT-C05', 'Hwapa', 'EXTERNAL', 'community', 'Shai-Osudoku District', NULL, NULL),
('EXT-C06', 'Manya-Jorpanya', 'EXTERNAL', 'community', 'Shai-Osudoku District', NULL, NULL),
('EXT-C07', 'Odumase', 'EXTERNAL', 'community', 'Shai-Osudoku District', NULL, NULL),
('EXT-C08', 'Wedokum', 'EXTERNAL', 'community', 'Shai-Osudoku District', NULL, NULL),
('EXT-H01', 'Ayikuma CHPS Compound', 'EXTERNAL', 'chps', 'Shai-Osudoku District', NULL, NULL),
('EXT-H02', 'St. Andrew Catholic Hospital, Kordiabe', 'EXTERNAL', 'mission_hospital', 'Shai-Osudoku District', NULL, NULL),
('EXT-H03', 'Doryumu CHPS Compound', 'EXTERNAL', 'chps', 'Shai-Osudoku District', NULL, NULL),
('EXT-H04', 'Kasunya CHPS Compound', 'EXTERNAL', 'chps', 'Shai-Osudoku District', NULL, NULL),
('EXT-H05', 'Volivo CHPS Compound', 'EXTERNAL', 'chps', 'Shai-Osudoku District', NULL, NULL),
('EXT-H06', 'Sota CHPS Compound', 'EXTERNAL', 'chps', 'Shai-Osudoku District', NULL, NULL),
('EXT-HC01', 'Duffor Health Centre', 'EXTERNAL', 'health_centre', 'Shai-Osudoku District', NULL, NULL),
('EXT-HC02', 'Agomeda Health Centre', 'EXTERNAL', 'health_centre', 'Shai-Osudoku District', NULL, NULL),
('EXT-HC03', 'Osudoku Health Centre', 'EXTERNAL', 'health_centre', 'Shai-Osudoku District', NULL, NULL),
('EXT-HC04', 'Asutsuare Health Centre', 'EXTERNAL', 'health_centre', 'Shai-Osudoku District', NULL, NULL),
('EXT-R01', 'Greater Accra Regional Hospital', 'EXTERNAL', 'regional_hospital', 'Accra', NULL, NULL),
('GATE-01', 'Ambulance Bay', 'INTERNAL', 'gateway', 'Shai-Osudoku District Hospital, Dodowa', NULL, NULL),
('INT-01', 'OPD Reception', 'INTERNAL', 'opd', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-02', 'Records Office', 'INTERNAL', 'opd', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-03', 'Triage Bay', 'INTERNAL', 'opd', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-04', 'Consulting Room A', 'INTERNAL', 'opd', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-05', 'Consulting Room B', 'INTERNAL', 'opd', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-06', 'Consulting Room C', 'INTERNAL', 'opd', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-07', 'Consulting Room D', 'INTERNAL', 'opd', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-08', 'Emergency / A&E', 'INTERNAL', 'emergency', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-09', 'Male Ward', 'INTERNAL', 'ward', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-10', 'Female Ward', 'INTERNAL', 'ward', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-11', 'Paediatric Ward', 'INTERNAL', 'ward', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-12', 'Maternity Ward', 'INTERNAL', 'ward', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-13', 'Lying-in Ward', 'INTERNAL', 'ward', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-14', 'Theatre 1', 'INTERNAL', 'theatre', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-15', 'Theatre 2', 'INTERNAL', 'theatre', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-16', 'Recovery Room', 'INTERNAL', 'theatre', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-17', 'Laboratory', 'INTERNAL', 'lab', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-18', 'Imaging / X-Ray', 'INTERNAL', 'lab', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-19', 'Ultrasound Unit', 'INTERNAL', 'lab', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-20', 'Pharmacy', 'INTERNAL', 'pharmacy', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-21', 'Drug Store', 'INTERNAL', 'pharmacy', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-22', 'Blood Bank', 'INTERNAL', 'store', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-23', 'Central Sterile Supply (CSSD)', 'INTERNAL', 'store', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-24', 'Mortuary', 'INTERNAL', 'support', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-25', 'Kitchen', 'INTERNAL', 'support', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-26', 'Laundry', 'INTERNAL', 'support', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-27', 'Biomedical Workshop', 'INTERNAL', 'support', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-28', 'General Stores', 'INTERNAL', 'store', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-29', 'Admin Block', 'INTERNAL', 'admin', 'Shai-Osudoku District Hospital', NULL, NULL),
('INT-30', 'Staff Room', 'INTERNAL', 'admin', 'Shai-Osudoku District Hospital', NULL, NULL);
