-- Resources seed data (real dataset: 30 rows)
INSERT INTO resources (resource_id, type, capacity, is_available, home_location_id)
VALUES
('RES-P01', 'porter', 1, TRUE, 'INT-01'),
('RES-P02', 'porter', 1, TRUE, 'INT-08'),
('RES-P03', 'porter', 1, TRUE, 'INT-09'),
('RES-P04', 'porter', 1, TRUE, 'INT-10'),
('RES-P05', 'porter', 1, TRUE, 'INT-11'),
('RES-P06', 'porter', 1, TRUE, 'INT-12'),
('RES-P07', 'porter', 1, TRUE, 'INT-13'),
('RES-P08', 'porter', 1, TRUE, 'INT-01'),
('RES-P09', 'porter', 1, TRUE, 'INT-08'),
('RES-P10', 'porter', 1, TRUE, 'INT-09'),
('RES-P11', 'porter', 1, TRUE, 'INT-10'),
('RES-P12', 'porter', 1, TRUE, 'INT-11'),
('RES-W01', 'wheelchair', 1, TRUE, 'INT-01'),
('RES-W02', 'wheelchair', 1, TRUE, 'INT-01'),
('RES-W03', 'wheelchair', 1, TRUE, 'INT-08'),
('RES-W04', 'wheelchair', 1, TRUE, 'INT-08'),
('RES-T01', 'trolley', 1, TRUE, 'INT-09'),
('RES-T02', 'trolley', 1, TRUE, 'INT-10'),
('RES-T03', 'trolley', 1, TRUE, 'INT-12'),
('RES-T04', 'trolley', 1, TRUE, 'INT-13'),
('RES-A01', 'ambulance', 2, TRUE, 'GATE-01'),
('RES-A02', 'ambulance', 1, TRUE, 'GATE-01'),
('RES-A03', 'ambulance', 1, TRUE, 'GATE-01'),
('RES-L01', 'lab_runner', 5, TRUE, 'INT-17'),
('RES-L02', 'lab_runner', 5, TRUE, 'INT-17'),
('RES-L03', 'lab_runner', 5, TRUE, 'INT-17'),
('RES-B01', 'biomedical_technician', 1, TRUE, 'INT-27'),
('RES-B02', 'biomedical_technician', 1, TRUE, 'INT-27'),
('RES-R01', 'pharmacy_rider', 5, TRUE, 'INT-20'),
('RES-R02', 'pharmacy_rider', 5, TRUE, 'INT-20');
