package gsoo.structures.b5_map;

/**
 * Slot B5 — trace demo.
 *
 * Uses real rows from sql/seed/resources_seed.sql (30-row resources dataset,
 * shipped by A3 on the `develop` branch). Maps resource_id -> capacity, since
 * that's a genuine key-value relationship straight from the seed data.
 *
 * This satisfies the Definition of Done requirement for trace output
 * "generated by the code from the real dataset."
 */
public class MapTraceDemo {

    public static void main(String[] args) {
        CustomMap<String, Integer> capacityByResourceId = new CustomMap<>();

        System.out.println("-- put (loading real resource records) --");
        put(capacityByResourceId, "RES-P01", 1);  // porter
        put(capacityByResourceId, "RES-A01", 2);  // ambulance
        put(capacityByResourceId, "RES-L01", 5);  // lab_runner
        put(capacityByResourceId, "RES-B01", 1);  // biomedical_technician
        put(capacityByResourceId, "RES-R01", 5);  // pharmacy_rider

        System.out.println("\n-- get --");
        System.out.println("RES-P01 -> " + capacityByResourceId.get("RES-P01"));
        System.out.println("RES-Z99 (not in dataset) -> " + capacityByResourceId.get("RES-Z99"));

        System.out.println("\n-- update existing key (ambulance capacity revised) --");
        put(capacityByResourceId, "RES-A01", 3);

        System.out.println("\n-- remove --");
        System.out.println("removed RES-B01 -> " + capacityByResourceId.remove("RES-B01"));

        System.out.println("\n-- final state --");
        for (Object keyObj : capacityByResourceId.keySet()) {
            String key = (String) keyObj;
            System.out.println(key + " : " + capacityByResourceId.get(key));
        }
        System.out.println("size = " + capacityByResourceId.size());
    }

    private static void put(CustomMap<String, Integer> map, String key, int value) {
        Integer previous = map.put(key, value);
        System.out.println("put(" + key + ", " + value + ") -> previous=" + previous);
    }
}